### ISSUE TITLE
Dropped support for ConnectX-3

### ISSUE THREAD

**Issue by andreybleme** [shenango/caladan#20]
Hi, is there a reason for dropping support for ConnectX-3? https://github.com/shenango/caladan/commit/e2846c088e99c74ea77206749bc542b7dea9bfab

Setting `CONFIG_MLX4=y` in `build/config`, cause the build error:

``` 
build/shared.mk:56: *** mlx4 support is not available currently.  Stop.
```

I'm not able to run Caladan on m510 Cloudlab machines anymore. m510 machines uses a Dual-port Mellanox ConnectX-3 10 GB NIC (https://docs.cloudlab.us/hardware.html)

Are we now required to use machines with Mellanox ConnectX-4, and set `CONFIG_MLX5=y`? Or is there a way to build Caladan using Mellanox ConnectX-3?

Thank you!

**Comment by joshuafried** [comment]
Hello,

We stopped supporting ConnectX-3 NICs because support for them was dropped in recent versions of the Mellanox OFED and it became difficult to continue developing the needed patches. The Cloudlab xl170 nodes have ConnectX-4 NICs that are still supported. You can also try running Caladan prior to that commit, though you may need to ensure that you have an older OS (Ubuntu 20.04 for example) that is supported by the older OFEDs (version 4.9 or earlier).

**Comment by andreybleme** [comment]
Thanks for clarifying that @joshuafried 🙌 

It worked on xl170.
